### ISSUE TITLE
Proposal: rename repository and image

### ISSUE THREAD

**Issue by funkyfuture** [samos123/docker-drupal#12]
as the image doesn't rely on tutum's php-image anymore, the name of the repository is a bit of misleading and outdated. i propose to name the github-repo and the Docker-image identically for clearness. as Drupal 8 comes closer, i'd also include an explicit reference to the major version. some thoughts:
- drupal7
- drupal-7
- drupal-seven

(nothing really sexy, but well.)

github will automaticall redirect to the new repository. anyone knows how the docker-registry handles this?

**Comment by cerisier** [comment]
I think you could rename to repo to drupal and handle version in subfolders like php or node does ?

**Comment by moul** [comment]
:+1: for `docker-drupal` name + a subfolder for each major version (7, 8, 9)

**Comment by samos123** [comment]
Tags and branches are enough for different versions, but I do agree that we
should remove tutum from the name.

Lets start a 8.x branch to also support 8.x and as soon as 8.x is
officially release, we make master/latest point same as 8.x

**Comment by funkyfuture** [comment]
i'd say a subfolder for each major release will make it easier to maintain two or more releases.

**Comment by samos123** [comment]
different versions can be done with tags and feature branches. I predict that there will be minor difference between versions and checking out branches / tags is superfast and convenient. We change the tarball url and md5. Your changes have helped a lot in making new versions supported easier.

I will create a 8.x branch to show that it's probably easier to maintain this way. I'm already working on it locally.

**Comment by funkyfuture** [comment]
i wouldn't assume that the differences between both major versions will just be subtle. my first assumption would be different system requirements.
but it could be split into different folders on the master-tree as soon as it get's too tricky.

i'm curious to take a peek on your work on 8.x

i'd also extend my proposal to provide two different image-flavors on the registry: one tagged `7.35` / `7.35-slim` / `latest` and another one tagged `7.35-foobar` (no good idea for the foobar yet). while the first one is targeted to be used as base-image, the other one targets people who just want to start a drupal-instance without cli-configuration.

**Comment by samos123** [comment]
See the 8.x branch I just pushed. I already made Drupal 8 latest beta kinda
working, there may  be still some issues.

**Comment by funkyfuture** [comment]
just one note on the `README.md`: it should be images in plural.
