### ISSUE TITLE
Proposal: dl & en modules after drush site-install

### ISSUE THREAD

**Issue by funkyfuture** [samos123/docker-drupal#14]
i think it would be nice to enable the users to simply auto-install a set of modules when a fresh site is created.
the list of modules would be read from `/contrib/modules.txt` _and_ an (csv-)environment variable.

i never used the [features-module](https://www.drupal.org/project/features). but maybe that could be considered as well.

**Comment by samos123** [comment]
yea this would make it easier to customize the image. I think we can just use drush for this to install and enable features provided by user.

**Comment by funkyfuture** [comment]
is anyone familiar with `drush make` and can assess how useful it'd be?

**Comment by samos123** [comment]
from my understanding we can't use it. Because when we build the drupal image we can not install modules / themes yet, because this has to happen at runtime when there is a db connected. A user could use drush make to extend this base image though.
