### ISSUE TITLE
Proposal: Bake in drush cron by default?

### ISSUE THREAD

**Issue by funkyfuture** [samos123/docker-drupal#15]
i'm not completely decided to an opinion on that:

using the `drush cron` command has the advantage that no user will be confronted with longer loading times when he/she has the luck to trigger the "Poor man's cron". some people insist on not using the latter one (performance fans). but with the image this could only be achieved with a host-cron that will trigger a `drush cron` with `docker exec`. not all of the possible users have access to the host system. 

by using _supervisord_ to run Apache and Cron simultaneously in one container, this could be solved. Cron will then trigger a `drush core-cron`.

of course this could be done with a derived image as well. but you know, i'm a friend of good defaults for accessibility. another solution could be to offer such images with a tag like `:7.35-cron`.

i'm looking for your feedback on this.

if there is some consent on implementing this, should the interval of the cron be configurable with an environment variable? e.g. `CRON_RUNS_PER_DAY`.

**Comment by samos123** [comment]
If there is a way to not use supervisord to run multiple services I would
prefer that. Instead of relying on drush we can also create a general
cronjob outside of the drupal image. Like defined here:
https://www.drupal.org/node/23714

45 * * * * curl -s http://example.com/cron.php

**Comment by funkyfuture** [comment]
would you prefer to start cron daemonized in `entrypoint.sh` (if possible?). what would be the advantage over supervisord?

a cron-config outside of an image can't be shipped (and shipping including all batteries is one thing Docker is about).

see my comment on #12, this would be a feature of a ready-to-run-image.

**Comment by samos123** [comment]
I was more thinking user should run a cron container which does the job.
It's out of scope for the drupal container. Just like how we separate the
DB from the drupal container.

There may be 1 to many drupal containers running. Should each container run
the cron? I believe there is only one cron job required.

**Comment by funkyfuture** [comment]
i'd like to agree on what you say as i prefer one container per service. but there is one pitfall. in order to trigger the cron via an url, that specific url must be known to the cron-container. but afaik this url will be presented to admins of the site in the ui for security reasons. i wouldn't yet know a way to set a specific cron-url.

me, myself and i are perfectly fine with a Poor Man's Cron. but an independent cron is considered more professional by those who like to drive ferrari on the web.

**Comment by samos123** [comment]
I mean what if this is a large scale website with a load balancer, it has
10 drupal containers running, 3 db containers(HA replicated) running and a
cron container, all these containers may be on different hosts. What I
meant to say is that not all 10 drupal containers should run a cron
service, but there should only be 1 cron service per website.

Is my example correct? If so we should not bake the cron service into the
drupal image.

**Comment by funkyfuture** [comment]
sounds reasonable. i'd really like to have an extra-container for that. but i have yet no clue how it would interact with the one webserver. see: https://www.drupal.org/node/158922

hm, on could do some research how to set the *cron_key* at site initialization or retrieve it from the database, where it is propably stored.

**Comment by samos123** [comment]
this is something that the orchestrator should do, he can use automation
tools to setup his whole stack, which is out of scope for this image. Maybe
when I have time I can do an example of a production ready HA stack with
multiple drupal containers, a cron container, haproxy load balancer and db.

**Comment by funkyfuture** [comment]
shall i leave this issue open as reminder for an example in the docs?

**Comment by samos123** [comment]
@funkyfuture did you come to a solution? if so we can add it to the docs but would be best from real experience not my theoretical solutions :p 

I'm still considering writing a blog post on using this image in something like Kubernetes with a Load Balancer, and multiple instances of our image.

**Comment by funkyfuture** [comment]
this (cron-)issue is still on my schedule and just bumped up. i will add the results to the docs.
