### ISSUE TITLE
Proposal: Consider upstreaming to docker-library/docker

### ISSUE THREAD

**Issue by funkyfuture** [samos123/docker-drupal#20]
ciao @samos123,

for a few days, there's an official Drupal-image in the docker-library. however it hardly has the capabilities of this one here.

i'm thinking about offering all features from here there. if they get accepted, and makes this image superfluous, that would be much less maintaining.

what ya think?

**Comment by samos123** [comment]
sure sounds like a good thing to do.

**Comment by funkyfuture** [comment]
you may leave your thoughts or just watch [here](https://github.com/docker-library/drupal/issues/2).

**Comment by samos123** [comment]
Seems they don't want most of the changes we did. They want it to be as close to drupal as possible. They most likely would prefer to have a drupal-drush image that's built on top of the drupal core image.

**Comment by funkyfuture** [comment]
i could close both issues as i don't expect they'l take much. but i'm still interested in an answer to a general design-guideline:

> by that opportunity, are there plans to publish guidelines what functionality an image from this library sould or must not provide?

i'll try to derive from that image and configure a web-hook. thus we wouldn't have to take care about core-updates anymore.

**Comment by funkyfuture** [comment]
i looked at the possibility to derive from the Docker library's Drupal-image. it would certainly be possible, but it would add more complexity than it's worth. furthermore we had to update this image's Dockerfile if they do change more than just updating the Drupal version.
