### ISSUE TITLE
Update Docker-Registry

### ISSUE THREAD

**Issue by funkyfuture** [samos123/docker-drupal#22]
there are some needs for updates on the Docker Registry page:

- version 7.37 is still not available
  - last build was on 10th of April
- description says the same
- could you add a word about Drush and maybe the bootstrapping in the description?

[my repo](https://registry.hub.docker.com/u/funkyfuture/drupal/builds_history/181553/) builds fine after pushing to github, so there seems to be an issue with your settings

**Comment by samos123** [comment]
I've updated registry and added the 7.37 tag, next to that I've synced our 7.x to branch to also be up to date with master 7.37 commit. Also updated the description to be the same as README

**Comment by funkyfuture** [comment]
thanks. but actually, the README is outdated on the registry at all. it still refers to `EXTRA_SETUP_SCRIPT`. i suggest to get the webhooks working in order to save you some trouble.

all the best!

**Comment by samos123** [comment]
thank you for maintaining this repo, I'm not using drupal at all anymore

**Comment by funkyfuture** [comment]
no problem for the foreseeable future. but it would help a lot if my pushes to the git-repo were automatically handled by your docker-registry-repo.

**Comment by samos123** [comment]
It seems because we renamed the repo it's unable to update automatically...

On Sat, May 30, 2015 at 9:51 PM, Frank Sachsenheim <notifications@github.com

**Comment by funkyfuture** [comment]
the README on the registry is very outdated, can you please trigger a build?!

btw, i [posted at the docker forums](https://forums.docker.com/t/how-would-one-change-the-linked-gh-bb-repo-of-a-docker-hub-repo/2168) regarding the renaming of a source repo. some weeks ago i asked a guy from Docker's support team to have a look at it and he answered that "we try to frequent the forums and answer questions whenever we have time"…

**Comment by samos123** [comment]
Thanks Funky for posting the problem on docker forums. The docker admin interface is only getting worse imo :P uur descriptiion exceeds the 5000 chars limit thats why it was unable to get udpated. I've removed the part Why create another drupal image for now. Build has also been retriggered.

In the future you can retrigger a build like this (Retriggers shouldn't matter, that's why we also use tags):
```
# Trigger all tags/branchs for this automated build.
$ curl -H "Content-Type: application/json" --data '&#123;"build": true&#125;' -X POST https://registry.hub.docker.com/u/samos123/drupal/trigger/0c826e7b-741d-481b-bce8-382c7bfe357c/

# Trigger by docker tag name
$ curl -H "Content-Type: application/json" --data '&#123;"docker_tag_name": "master"&#125;' -X POST https://registry.hub.docker.com/u/samos123/drupal/trigger/0c826e7b-741d-481b-bce8-382c7bfe357c/

# Trigger by Source branch named staging
$ curl -H "Content-Type: application/json" --data '&#123;"source_type": "Branch", "source_name": "staging"&#125;' -X POST https://registry.hub.docker.com/u/samos123/drupal/trigger/0c826e7b-741d-481b-bce8-382c7bfe357c/

# Trigger by Source tag named v1.1
$ curl -H "Content-Type: application/json" --data '&#123;"source_type": "Tag", "source_name": "v1.1"&#125;' -X POST https://registry.hub.docker.com/u/samos123/drupal/trigger/0c826e7b-741d-481b-bce8-382c7bfe357c/
```

**Comment by funkyfuture** [comment]
okay, i’ll save that.

we could move some of the docs to extra files, if necessary.

yeah, now that all images are actually found, it’s almost impossible to find what may be of interest to you
