### ISSUE TITLE
Postgres doesn't launch quite correctly.

### ISSUE THREAD

**Issue by erasche** [samos123/docker-drupal#25]
In [f33e2dd](https://github.com/funkyfuture/docker-drupal/commit/f33e2dd542ee4f68bd80435b3c974093f16ffab5#diff-b958f585a04af5ee2087610ea7180f34L120) the (admittedly ugly) postgres query I'd written:

```basg
drush sql-query --result-file='table-query.txt' '\dt';
lines=$(wc -l table-query.txt | sed 's/ .*//g')
if [[ $lines -eq 0 ]]; then
	run_scripts setup
else
	echo "=> Skipped setup - table drupal already exists."
fi
```

was changed to:

```
drush sql-query '\l' > /dev/null || TABLE_EXISTS=$?
```

which does not have the desired effect. That escaped my notice, I didn't test well enough/review closely enough. (That's on me, my bad.) That will (just about) 100% of the time exit 0, and doesn't answer the question which really needs to be asked. 

Running that in an empty postgres container:

```
root@7ac75f356aa0:/# psql -U postgres -c '\l'
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)
```

you see the default database that's part of the base image (could be named something other than postgres via an undocumented environment variable), and the two templates which are always there.

According to the postgres docs:

> \l[+] or \list[+] [ pattern ]
> List the databases in the server and show their names, owners, character set encodings, and access privileges. ...

Postgres functions __fundamentally__ differently to mysql. As mentioned in https://github.com/samos123/docker-drupal/pull/23#issuecomment-122045044 the better analogue to mysql databases is postgres schemas, whcih can be queried via `\dn`:

```
root@7ac75f356aa0:/# psql -U postgres -c '\dn' 
  List of schemas
  Name  |  Owner   
--------+----------
 public | postgres
(1 row)
```

however, again, that will (just about) always exit successfully. The `public` schema is available by default. The change introduced in f33e2dd must be reverted if the drupal+chado is to function at all. It always returns 0, so the code assumes that "tables are found" even when they're not: (`\dt` actually checks for tables)

```
root@7ac75f356aa0:/# psql -U postgres -c '\dt' 
No relations found.
root@7ac75f356aa0:/# echo $?
0
```

## Planned change

I plan to change this back to `\dt` and saving to a temporary file. 

Proof that this is what's required if you really want to check for tables being there (which is an improvement over mysql)

```bash
root@7c4325ae33e4:/var/www/html# drush sql-query --result-file='table-query.txt' '\dt'
root@7c4325ae33e4:/var/www/html# if [[ -s 'table-query.txt' ]]; then echo "data"; else echo "empty"; fi;
empty
root@7c4325ae33e4:/var/www/html# drush sql-query 'create table test(id int);'
root@7c4325ae33e4:/var/www/html# drush sql-query --result-file='table-query.txt' '\dt' 
root@7c4325ae33e4:/var/www/html# if [[ -s 'table-query.txt' ]]; then echo "data"; else echo "empty"; fi;
data
root@7c4325ae33e4:/var/www/html# cat table-query.txt 
public  test    table   postgres
```

vs `\l` on a fresh database:

```
root@7c4325ae33e4:/var/www/html# drush sql-query --result-file='table-query.txt' '\l' 2&> /dev/null 
root@7c4325ae33e4:/var/www/html# echo $?
0
root@7c4325ae33e4:/var/www/html# cat table-query.txt 
postgres        postgres        UTF8    en_US.utf8      en_US.utf8
template0       postgres        UTF8    en_US.utf8      en_US.utf8      =c/postgres
postgres=CTc/postgres
template1       postgres        UTF8    en_US.utf8      en_US.utf8      =c/postgres
postgres=CTc/postgres
```

## Supporting information

> MySQL aliases schema with database behind the scenes, such that CREATE SCHEMA and CREATE DATABASE are analogs. It can therefore be said that MySQL has implemented cross-database functionality, skipped schema functionality entirely, and provided similar functionality into their implementation of a database. In summary, Postgres fully supports schemas but lacks some functionality MySQL has with databases, while MySQL does not even attempt to support true schemas.

https://en.wikipedia.org/wiki/Comparison_of_relational_database_management_systems#Databases_vs_schemas_.28terminology.29

**Comment by erasche** [comment]
There's additionally a bug in the exit-code check:

```bash
$ if ! $TABLE_EXISTS; then echo "a"; else echo "b"; fi
1: command not found
a
$ TABLE_EXISTS=0
$ if ! $TABLE_EXISTS; then echo "a"; else echo "b"; fi
0: command not found
a
```

https://github.com/samos123/docker-drupal/blob/master/entrypoint.sh#L131

**Comment by funkyfuture** [comment]
that's odd, i tested it with a postgres-config as in the example-folder and it worked.

have you checked it out from scratch? are you using a postgres-host with other databases present?

i'd prefer if you were not using a temporary file, but rather process stdout through pipes.

**Comment by erasche** [comment]
Odd indeed. Yes, clean copy of the repository, I reset `--hard` to origin/master, built the image, things were acting up.

It's an empty postgres image. There is a database by default, `postgres`, with a schema by default, `public`. It's how postgres works.

What's the rationale for pipes over a temporary file that gets created and cleaned up safely? 

I could do it like this:

```bash
NUMBER_OF_CHARS=$(drush sql-query '\dt*' | wc -c)
# because `drush sql-query | wc -l` returns 1 if there are zero tables AND if there's 1 table
# we have to use `wc -c` 
if [[ $NUMBER_OF_CHARS -eq 1 ]]; then
  # i.e. no lines   TABLE_EXISTS=1
else
  TABLE_EXISTS=0;
fi
```

is that what you'd really prefer?


```
root@64e89c342e43:/var/www/html# drush sql-query '\dt' 2>/dev/null | wc -l
74
root@64e89c342e43:/var/www/html# drush sql-query 'drop schema public cascade; create schema public;'
# deletes all the tables
root@64e89c342e43:/var/www/html# drush sql-query '\dt' 2>/dev/null | wc -l
1
root@64e89c342e43:/var/www/html# drush sql-query '\dt' 2>/dev/null        

# 1 is an odd number for an empty output...let's check 
root@64e89c342e43:/var/www/html# drush sql-query 'create table blah(id int);' 2>/dev/null 

root@64e89c342e43:/var/www/html# drush sql-query '\dt' 2>/dev/null                        
public  blah    table   postgres
root@64e89c342e43:/var/www/html# drush sql-query '\dt' 2>/dev/null | wc -l
1
root@64e89c342e43:/var/www/html# 

```

`-_-` I am not a fan of drush so far.

**Comment by funkyfuture** [comment]
i change to the project's directory.

this is my `master`'s HEAD: 8173c2ce25fe24d2e9b364cacbc9c96840989bf3

then i change `docker-compose.yml` to this:

```yaml
# This is a sample configuration to run a Drupal-instance with Docker-Compose.
# For customization options see: https://docs.docker.com/compose/yml/

web:
  build: .
  links:
    - db:postgres
  volumes:
    - /var/www/html/sites
    - /var/www/private
  environment:
    - UPLOAD_LIMIT=20M
    - MEMORY_LIMIT=128M
    - VIRTUAL_HOST=test.docker.lan
    - BASE_URL_PROTO=http://

db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=password
  volumes:
    - /var/lib/postgresql/data
```

then i run `docker-compose rm && docker-compose build && docker-compose up`

and now i could look at a fresh Drupal's site. but it's in another browser-tab. (i checked, it's there.)

please try to reproduce.
